### ISSUE TITLE
Error while running the source

### ISSUE THREAD

**Issue by suresh-s** [okkam-it/flink-examples#5]
I have compiled using the command "mvn clean compile -Dcheckstyle.skip"

If i right click the file "KafkaFlinkAvroParquet.java" and run in Intellij, I am getting following error.

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/flink/queryablestate/network/stats/KvStateRequestStats
	at org.apache.flink.runtime.taskexecutor.TaskManagerRunner.startTaskManager(TaskManagerRunner.java:365)
	at org.apache.flink.runtime.minicluster.MiniCluster.startTaskManagers(MiniCluster.java:801)
	at org.apache.flink.runtime.minicluster.MiniCluster.start(MiniCluster.java:325)
	at org.apache.flink.streaming.api.environment.LocalStreamEnvironment.execute(LocalStreamEnvironment.java:120)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.execute(StreamExecutionEnvironment.java:1510)
	at it.okkam.flink.KafkaFlinkAvroParquet.main(KafkaFlinkAvroParquet.java:63)
Caused by: java.lang.ClassNotFoundException: org.apache.flink.queryablestate.network.stats.KvStateRequestStats
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more

Could you help me to execute ?

**Comment by fpompermaier** [comment]
I'll  check it right now

**Comment by fpompermaier** [comment]
Maybe it because of the way Eclipse and Intellij manage the depenedency scopes.
Try to change **provided** to **runtime** in pom.xml and let me know..I found that the flink quickstart archetype comes with scope=runtime that causes problem to Eclipse and I had to change it to provided to make it work

**Comment by fpompermaier** [comment]
I also fixed the pom.xml because it was missing the avro.version value in the properties and maybe this causes problems to the compilation of the project..try to update to the latest commit of the master branch

**Comment by suresh-s** [comment]
I already have changed the avro.version.  

I have changed from **provided** to **runtime** in pom.xml as you mentioned. 
I am getting following error **"mvn clean compile -Dcheckstyle.skip"**.   If i am keeping "**provided**" as it is, Build is successful.

[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/sureshs/Documents/source/flink-examples/src/main/java/com/dataartisans/queryablestatedemo/EventCountClient.java:[27,46] package org.apache.flink.queryablestate.client does not exist
[ERROR] /Users/sureshs/Documents/source/flink-examples/src/main/java/com/dataartisans/queryablestatedemo/EventCountClient.java:[43,11] cannot find symbol
  symbol:   class QueryableStateClient
  location: class com.dataartisans.queryablestatedemo.EventCountClient
[ERROR] /Users/sureshs/Documents/source/flink-examples/src/main/java/com/dataartisans/queryablestatedemo/EventCountClient.java:[43,45] cannot find symbol
  symbol:   class QueryableStateClient
  location: class com.dataartisans.queryablestatedemo.EventCountClient
[INFO] 3 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.242 s
[INFO] Finished at: 2019-06-24T15:24:47+05:30
[INFO] Final Memory: 38M/371M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project flink-examples: Compilation failure: Compilation failure: 
[ERROR] /Users/sureshs/Documents/source/flink-examples/src/main/java/com/dataartisans/queryablestatedemo/EventCountClient.java:[27,46] package org.apache.flink.queryablestate.client does not exist
[ERROR] /Users/sureshs/Documents/source/flink-examples/src/main/java/com/dataartisans/queryablestatedemo/EventCountClient.java:[43,11] cannot find symbol
[ERROR]   symbol:   class QueryableStateClient
[ERROR]   location: class com.dataartisans.queryablestatedemo.EventCountClient
[ERROR] /Users/sureshs/Documents/source/flink-examples/src/main/java/com/dataartisans/queryablestatedemo/EventCountClient.java:[43,45] cannot find symbol
[ERROR]   symbol:   class QueryableStateClient
[ERROR]   location: class com.dataartisans.queryablestatedemo.EventCountClient
[ERROR] -> [Help 1]

**Comment by fpompermaier** [comment]
I've tried to checkout the project, run  mvn clean compile -Dcheckstyle.skip adn I didn't get any errors.. (I'm using apache-maven-3.3.9)
